//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MapTool.rc
//
#define ID_FILE_LOAD                    0
#define IDD_ABOUTBOX                    100
#define IDD_DLG_SETUP                   103
#define IDR_MAINFRAME                   128
#define IDR_MapToolTYPE                 129
#define IDD_DLG_NEWTERRAIN              130
#define IDD_DLG_MAINTAB                 131
#define IDD_DLG_MT_HEIGHT               132
#define IDD_DLG_MT_MAPING               133
#define IDD_DLG_MTMAP_SELVIEW           134
#define IDD_DLG_MT_MAIN                 138
#define IDR_MENU1                       139
#define IDD_DLG_EDIT                    141
#define IDD_DLG_MT_OBJECT               143
#define IDD_DLG_NODE                    144
#define IDI_ICON1                       144
#define IDI_ICON_SPOID                  144
#define IDD_DLG_MT_SHADOW               145
#define IDD_DLG_NOTICE                  146
#define IDD_DLG_OBJECT_CONTROL          147
#define IDD_DLG_CONFIG                  148
#define IDD_DLG_INPUTKEY                149
#define IDD_DLG_MT_PLAYER               150
#define IDD_DLG_MT_ETC                  151
#define IDD_DLG_MT_MODEL                152
#define IDD_DLG_MT_MAP_BUFF_REGION      155
#define IDD_DLG_MT_OBJECT_PORTAL        158
#define IDD_DLG_MT_MAP                  159
#define IDD_DLG_MT_MAP_START            160
#define IDD_DLG_MT_MONSTER              161
#define IDD_DLG_MT_MAP_REGION           162
#define IDD_DLG_MT_PATH                 163
#define IDD_DLG_MT_HEIGHT_REGION        164
#define IDD_DLG_MT_HEIGHT_POLYGON       165
#define IDD_DLG_MT_OBJECT_TEXTYPE       166
#define IDD_DLG_MT_OBJECT_MERGE         167
#define IDD_DLG_MT_MAP_RESURRECTION     168
#define IDD_DLG_MT_LIGHT                169
#define IDD_DLG_MT_LIGHT_DIRECTION      170
#define IDD_DLG_MT_LIGHT_POINT          171
#define IDD_DLG_MT_OBJECT_ANI           172
#define IDD_DLG_MT_CELL_OBJECT          173
#define IDD_DLG_OBJECT_LIST             174
#define IDD_DLG_MT_MODEL_PORTAL         175
#define IDD_DLG_MT_MAP_LIMITEVO         176
#define IDD_DLG_MT_WEATHER              177
#define IDC_EDIT_TWIDTH                 1000
#define IDC_EDIT_THEIGHT                1001
#define IDC_EDIT_GRIDWIDTH              1002
#define IDC_EDIT_XVERT                  1003
#define IDC_COMBO_TREELEVEL             1004
#define IDC_EDIT_YVERT                  1005
#define IDC_BTN_APPLY_MAKESET           1006
#define IDC_EDIT_XVERT_STRUCT           1007
#define IDC_COMBO_BASE_MPPG             1007
#define IDC_EDIT_YVERT_STRUCT           1008
#define IDC_COMBO_ALPHA_MPPG            1008
#define IDC_BTN_OK                      1009
#define IDC_BTN_CANCEL                  1010
#define IDC_TAB_MAIN                    1011
#define IDC_BTN_HEIGHTMAP_LOAD          1013
#define IDC_EDIT_HEIGHTMAP_PATH         1014
#define IDC_BTN_HEIGHTMAP_REAPPLY       1015
#define IDC_EDIT_HEIGHT_RATE            1016
#define IDC_BTN_HEIGHTMAP_REAPPLY_SHADOWMAP 1017
#define IDC_BTN_BASEMAP                 1020
#define IDC_BTN_ALPHAMAP                1022
#define IDC_BTN_SECONDMAP               1023
#define IDC_STATIC_BASE                 1027
#define IDC_STATIC_ALPHA                1028
#define IDC_STATIC_BASE2                1031
#define IDC_BTN_TEXTYPE                 1032
#define IDC_STATIC_ALPHA2               1033
#define IDC_BTN_ROT1                    1034
#define IDC_BTN_ROT2                    1035
#define IDC_BTN_NEW                     1035
#define IDC_BTN_PLAYVIEW                1036
#define IDC_BTN_RELOAD                  1036
#define IDC_BTN_PATCH_NOTE              1037
#define IDC_BTN_LOADTERRAIN             1038
#define IDC_BTN_LOAD                    1038
#define IDC_BTN_SAVE                    1039
#define IDC_BTN_MAKE_CIFILE             1040
#define IDC_BTN_SAVEAS                  1041
#define IDC_BTN_TR_MERGE                1042
#define IDC_EDIT_DATA                   1048
#define IDC_LIST_MAPINFO                1054
#define IDC_STATIC_VERSION              1056
#define IDC_BTN_ADD_OBJECT              1057
#define IDC_TREE_OBJECT                 1058
#define IDC_DLG_SETUP                   1058
#define IDC_BTN_DELETE_ALL              1059
#define IDC_TREE_TEXTURE                1060
#define IDC_BTN_ADD_TEXTURE             1061
#define IDC_TREE_NODE                   1062
#define IDC_EDIT_WIDTH                  1063
#define IDC_EDIT_HEIGHT                 1064
#define IDC_EDIT_BIT                    1065
#define IDC_BUTTON_SET_DMAP0            1065
#define IDC_RADIO_DMAP1                 1066
#define IDC_BUTTON_SET_DMAP1            1067
#define IDC_RADIO_DMAP2                 1069
#define IDC_BUTTON_SET_DMAP2            1070
#define IDC_RADIO_DMAP3                 1071
#define IDC_BUTTON_SET_DMAP3            1072
#define IDC_SLD_SIZE                    1073
#define IDC_SLD_DECREMENT               1074
#define IDC_EDIT_SIZE                   1075
#define IDC_SLD_FOG_ENDOBJECT           1075
#define IDC_EDIT_DECREMENT              1076
#define IDC_SLD_CLIP_OBJECT             1076
#define IDC_BUTTON_APPLY                1077
#define IDC_RADIO_GRAY                  1077
#define IDC_EDIT_FOG_ENDOBJECT          1077
#define IDC_SLD_MAP_SIZE                1078
#define IDC_SLD_FOG_ENDTERRAIN          1078
#define IDC_STATIC_NOTICE               1079
#define IDC_RADIO_WHITE                 1079
#define IDC_EDIT_FOG_ENDTERRAIN         1079
#define IDC_PROGRESS_BAR                1080
#define IDC_EDIT_SIZE2                  1080
#define IDC_EDIT_MAP_SIZE               1080
#define IDC_EDIT_CLIP_OBJECT            1080
#define IDC_BUTTON_SMBLUR_APPLY         1080
#define IDC_EDIT_SHADOW_CONSTANT        1081
#define IDC_SLD_CLIP_TERRAIN            1081
#define IDC_RADIO_DMAP4                 1081
#define IDC_EDIT_CLIP_TERRAIN           1082
#define IDC_BUTTON_SMBLUR_BACK          1082
#define IDC_BUTTON_SET_DMAP4            1082
#define IDC_STATIC_SHADOWCOLOR          1083
#define IDC_SLD_CLIP_CELL               1083
#define IDC_SLD_MAP_OP                  1083
#define IDC_CHECK_RENDEROBJECT          1084
#define IDC_STATIC_LIGHT_D              1084
#define IDC_EDIT_CLIP_CELL              1084
#define IDC_EDIT_MAP_OP                 1084
#define IDC_STATIC_LIGHT_A              1085
#define IDC_STATIC_LIGHT_GA             1086
#define IDC_EDIT_ROT_X                  1087
#define IDC_CHECK_LIGHT_DIR             1087
#define IDC_STATIC_TRSCOLOR             1088
#define IDC_BUTTON_DELETE               1089
#define IDC_EDIT_ROT_Y                  1090
#define IDC_EDIT_ROT_Z                  1091
#define IDC_EDIT_TL_X                   1092
#define IDC_EDIT_TL_Y                   1093
#define IDC_EDIT_TL_Z                   1094
#define IDC_EDIT_SCALE                  1095
#define IDC_EDIT_C                      1095
#define IDC_RADIO_DMAP0                 1096
#define IDC_EDIT_POWER                  1096
#define IDC_EDIT_RANDOM_SCALE_MIN       1096
#define IDC_EDIT_OBJID                  1096
#define IDC_COMBO_DECREASE_CONSTANT     1097
#define IDC_EDIT_RANDOM_SCALE_MAX       1097
#define IDC_COMBO_SHADOW_MPPG           1098
#define IDC_COMBO_MPPG                  1098
#define IDC_EDIT_RANDOM_XROT_MIN        1098
#define IDC_EDIT_RANDOM_XROT_MAX        1099
#define IDC_COMBO_BASEMPPG              1099
#define IDC_BUTTON_SWAP_12              1100
#define IDC_EDIT_RANDOM_YROT_MIN        1100
#define IDC_BUTTON_SWAP_23              1101
#define IDC_EDIT_KS_OBJ1                1101
#define IDC_EDIT_RANDOM_YROT_MAX        1101
#define IDC_BUTTON_SWAP_13              1102
#define IDC_EDIT_KS_OBJ2                1102
#define IDC_EDIT_RANDOM_ZROT_MIN        1102
#define IDC_EDIT_KS_OBJ3                1103
#define IDC_EDIT_RANDOM_ZROT_MAX        1103
#define IDC_EDIT_KS_OBJ4                1104
#define IDC_EDIT_RANDOM_ZTRANS_MIN      1104
#define IDC_STATIC_KEY0                 1105
#define IDC_EDIT_RANDOM_ZTRANS_MAX      1105
#define IDC_STATIC_KEY1                 1106
#define IDC_EDIT_GROUP_COUNT            1106
#define IDC_STATIC_KEY2                 1107
#define IDC_EDIT_CHECK_TIME_MIN         1107
#define IDC_STATIC_KEY3                 1108
#define IDC_EDIT_CHECK_TIME_MAX         1108
#define IDC_STATIC_KEY4                 1109
#define IDC_EDIT_ANI_SPEED_MIN          1109
#define IDC_STATIC_KEY5                 1110
#define IDC_EDIT_ANI_SPEED_MAX          1110
#define IDC_STATIC_KEY6                 1111
#define IDC_BUTTON_DEFAULT_KEY          1112
#define IDC_CHECK_USE_AUTOSAVE          1113
#define IDC_EDIT_AUTOSAVE_MIN           1114
#define IDC_STATIC_KEY7                 1115
#define IDC_STATIC_GRAYCOLOR            1115
#define IDC_STATIC_KEY8                 1116
#define IDC_BUTTON_CREATE_HEIGHT_FIELD  1116
#define IDC_STATIC_KEY9                 1117
#define IDC_COMBO_TEXTURE_TYPE1         1117
#define IDC_STATIC_KEY10                1118
#define IDC_BUTTON_APPLY_COLLISION      1118
#define IDC_STATIC_KEY11                1119
#define IDC_COMBO_TEXTURE_TYPE2         1119
#define IDC_BUTTON_MAKE_MINIMAP         1119
#define IDC_STATIC_KEY12                1120
#define IDC_COMBO_TEXTURE_TYPE3         1120
#define IDC_BUTTON_MAKE_FEMR            1120
#define IDC_STATIC_KEY13                1121
#define IDC_COMBO_TEXTURE_TYPE4         1121
#define IDC_STATIC_KEY14                1122
#define IDC_COMBO_TEXTURE_TYPE5         1122
#define IDC_EDIT_SKYBOX_PATH            1122
#define IDC_STATIC_KEY15                1123
#define IDC_COMBO_TEXTURE_TYPE6         1123
#define IDC_BTN_LOADSKYBOX              1123
#define IDC_STATIC_KEY16                1124
#define IDC_COMBO_TEXTURE_TYPE7         1124
#define IDC_STATIC_KEY17                1125
#define IDC_COMBO_TEXTURE_TYPE0         1125
#define IDC_SLD_FOG_START               1126
#define IDC_EDIT_SLEEPTICK              1127
#define IDC_EDIT_FOG_START              1127
#define IDC_STATIC_FOG_COLOR            1128
#define IDC_STATIC_KEY38                1128
#define IDC_EDIT_FEMR_DIST              1129
#define IDC_STATIC_KEY39                1129
#define IDC_STATIC_BG_COLOR             1129
#define IDC_STATIC_KEY40                1130
#define IDC_STATIC_KEY18                1135
#define IDC_STATIC_KEY22                1136
#define IDC_STATIC_KEY19                1137
#define IDC_STATIC_KEY20                1138
#define IDC_STATIC_KEY21                1139
#define IDC_STATIC_KEY23                1140
#define IDC_STATIC_KEY24                1141
#define IDC_STATIC_KEY25                1142
#define IDC_STATIC_KEY26                1143
#define IDC_STATIC_KEY27                1144
#define IDC_STATIC_KEY28                1145
#define IDC_STATIC_KEY29                1146
#define IDC_COMBO_MAPID                 1146
#define IDC_STATIC_KEY30                1147
#define IDC_EDIT_MAPNAME                1147
#define IDC_STATIC_KEY31                1148
#define IDC_EDIT_MAP_DESCRIPTION        1148
#define IDC_STATIC_KEY32                1149
#define IDC_EDIT_BGSOUND                1149
#define IDC_STATIC_KEY33                1150
#define IDC_COMBO_RESURRECTION          1150
#define IDC_STATIC_KEY34                1151
#define IDC_LIST_UNIQ_OBJ               1151
#define IDC_STATIC_KEY35                1152
#define IDC_COMBO_UNIQ_OBJ              1152
#define IDC_STATIC_KEY36                1153
#define IDC_SLIDER_RADIUS               1153
#define IDC_COMBO_ELE_LEVEL             1153
#define IDC_EDIT_MAP_DESCRIPTION2       1153
#define IDC_EDIT_MAP_DESCRIPTION_ENG    1153
#define IDC_STATIC_KEY37                1154
#define IDC_EDIT_STARTX                 1155
#define IDC_EDIT_STARTY                 1156
#define IDC_BUTTON_ADD_UNIQOBJ          1158
#define IDC_EDIT_RADIUS                 1158
#define IDC_BUTTON_ADD_ZONE             1159
#define IDC_COMBO_MAP                   1160
#define IDC_BUTTON_DEL_ZONE             1160
#define IDC_BUTTON_BACK_ORGTR           1161
#define IDC_EDIT_DESTX                  1162
#define IDC_BUTTON_ADD_ELEMENT          1162
#define IDC_EDIT_DESTY                  1163
#define IDC_BUTTON_DEL_ELEMENT          1163
#define IDC_BUTTON_GOTO_DESTMAP         1164
#define IDC_BUTTON_DEL_UNIQOBJ          1164
#define IDC_EDIT_TOTALCOUNT             1165
#define IDC_LIST_MONSTER                1165
#define IDC_LIST_RESIST_MONSTOR         1166
#define IDC_EDIT_PORTAL_ID              1166
#define IDC_SLIDER_REGIONSIZE           1167
#define IDC_EDIT_REGIONSIZE             1168
#define IDC_BUTTON_RESISTDELETE         1169
#define IDC_EDIT_MONCOUNT               1170
#define IDC_EDIT_MONRESPONTIME          1171
#define IDC_CHECK_WRITE_EXCEL           1171
#define IDC_EDIT_DEF_MONCOUNT           1172
#define IDC_CHECK_WRITE_LIST            1172
#define IDC_SPIN_ROT_X                  1173
#define IDC_EDIT_DEF_MONRESPONTIME      1173
#define IDC_CHECK_WRITE_PORTAL          1173
#define IDC_LIST_NPCLIST                1174
#define IDC_SLIDER_DEF_REGIONSIZE       1174
#define IDC_CHECK_WRITE_CHARLIGHT       1174
#define IDC_BUTTON_LOADBGSOUND          1175
#define IDC_EDIT_DEF_REGIONSIZE         1175
#define IDC_LIST_ELEMENT                1175
#define IDC_EDIT_MAP_REGION_DISCRIPT    1176
#define IDC_SLIDER_MONSCALE             1176
#define IDC_SPIN_ROT_Y                  1177
#define IDC_EDIT_REGION_BGSOUND         1177
#define IDC_EDIT_MONSCALE               1177
#define IDC_SPIN_ROT_Z                  1178
#define IDC_BUTTON_LOAD_REGION_BGSOUND  1178
#define IDC_BUTTON_RESISTALLDELETE      1178
#define IDC_SPIN_TL_X                   1179
#define IDC_BUTTON_DEL_REGION_BGSOUND   1179
#define IDC_EDIT_KILLGEN_ID             1179
#define IDC_SPIN_TL_Y                   1180
#define IDC_BUTTON_DEL_BGSOUND          1180
#define IDC_SPIN_ET                     1180
#define IDC_EDIT_KILLGEN_COUNT          1180
#define IDC_EDIT_MAP_REGION_DISCRIPT_ENG 1180
#define IDC_SPIN_TL_Z                   1181
#define IDC_SPIN_ER                     1181
#define IDC_EDIT_KILLGEN_VIEWCNT        1181
#define IDC_SPIN_EB                     1182
#define IDC_SPIN_SCALE                  1182
#define IDC_SPIN_C                      1182
#define IDC_EDIT_MOVE                   1182
#define IDC_COMBO_SMBLUR_SIZE           1183
#define IDC_SPIN_PY                     1183
#define IDC_SPIN_POWER                  1183
#define IDC_SPIN_RANDOM_SCALE_MIN       1183
#define IDC_EDIT_DEF_MOVE               1183
#define IDC_EDIT_OBJECT_PATH            1184
#define IDC_SPIN_RANDOM_SCALE_MAX       1184
#define IDC_SPIN_RANDOM_XROT_MIN        1185
#define IDC_EDIT_OBJECT_NAME            1185
#define IDC_SPIN_RANDOM_XROT_MAX        1186
#define IDC_SPIN_RANDOM_YROT_MIN        1187
#define IDC_LIST_TERRAINPATH            1188
#define IDC_SPIN_RANDOM_YROT_MAX        1188
#define IDC_CHECK_RESIST_PATH           1189
#define IDC_SPIN_RANDOM_ZROT_MIN        1189
#define IDC_BUTTON_DEL_PATH             1190
#define IDC_SPIN_RANDOM_ZROT_MAX        1190
#define IDC_EDIT_TERRAINPATH_HEIGHT     1191
#define IDC_SPIN_RANDOM_ZTRANS_MIN      1191
#define IDC_SPIN_TERRAINPATH_HEIGHT     1192
#define IDC_SPIN_RANDOM_ZTRANS_MAX      1192
#define IDC_BUTTON_RESET_OBJECTPATH     1193
#define IDC_SPIN_CHECK_TIME_MIN         1193
#define IDC_SPIN_CHECK_TIME_MAX         1194
#define IDC_BUTTON_DEL_PATH_ALL         1194
#define IDC_BUTTON_RESET_MAXPATH        1195
#define IDC_SPIN_ANI_SPEED_MIN          1195
#define IDC_EDIT_OBJECTPATH_HEIGHT      1196
#define IDC_SPIN_ANI_SPEED_MAX          1196
#define IDC_SPIN_OBJECTPATH_HEIGHT      1197
#define IDC_COMBO_USERHEIGHT_TYPE       1197
#define IDC_EDIT_MAXPATH_HEIGHT         1198
#define IDC_SPIN_MAXPATH_HEIGHT         1199
#define IDC_BUTTON_RESET_TERRAINPATH    1200
#define IDC_EDIT_DELTA_HEIGHT           1203
#define IDC_SLIDER_DELTA_HEIGHT         1205
#define IDC_SLIDER_SIZE                 1209
#define IDC_EDIT_CONSTANT               1210
#define IDC_SLIDER_CONSTANT             1211
#define IDC_CHECK_SET_LIMITE            1212
#define IDC_EDIT_LIMITE                 1213
#define IDC_BUTTON_RELEASE_LIMITE       1214
#define IDC_RADIO_UP_LIMITE             1215
#define IDC_RADIO_DOWN_LIMITE           1216
#define IDC_COMBO_HEIGHT_TYPE           1217
#define IDC_LIST_USERDEFINE             1218
#define IDC_COMBO_OBJECT_TYPE           1220
#define IDC_LIST_MERGE                  1223
#define IDC_CHECK_USE_SNAP              1224
#define IDC_EDIT_SNAP_SIZE              1225
#define IDC_CHECK_INCLUDE_TERRAIN       1226
#define IDC_EDIT_SELECT_COUNT           1226
#define IDC_CHECK_USE_TOGGLE            1227
#define IDC_SPIN_EL                     1230
#define IDC_SPIN_EROT                   1231
#define IDC_SPIN_PX                     1233
#define IDC_BUTTON_GRAY_CLEAR           1233
#define IDC_SPIN_GARY                   1234
#define IDC_EDIT_SKYBOX_HEIGHT          1235
#define IDC_SPIN_SKYBOX_HEIGHT          1236
#define IDC_STATIC_SL_D                 1242
#define IDC_STATIC_SL_A                 1243
#define IDC_STATIC_SL_S                 1244
#define IDC_LIST_LIGHT                  1246
#define IDC_CREATEMODE                  1247
#define IDC_CM_OK                       1248
#define IDC_CM_CANCEL                   1249
#define IDC_COMBO_TYPE                  1250
#define IDC_CHECK_TR                    1252
#define IDC_CHECK_OBJECT                1253
#define IDC_CHECK_CHAR                  1254
#define IDC_CHECK_OBJECT_SHADOW         1255
#define IDC_EDIT_RANGE                  1256
#define IDC_SPIN_RANGE                  1257
#define IDC_BUTTON_LISTDEL              1258
#define IDC_CHECK_DYNAMIC_SHADOW        1258
#define IDC_CHECK_SETPOS                1259
#define IDC_BUTTON_LIST_COPY            1260
#define IDC_BUTTON_APPLY_LIGHT_AMBIENT  1261
#define IDC_BUTTON_CANCEL               1262
#define IDC_CHECK1                      1263
#define IDC_SLIDER_ANISPEED             1264
#define IDC_EDIT_ANISPEED               1265
#define IDC_SLIDER_FRAME                1266
#define IDC_EDIT_FRAME                  1267
#define IDC_LIST_CELLOBJECT             1269
#define IDC_CHECK_RANDOM_SCALE          1270
#define IDC_CHECK_RANDOM_XROT           1271
#define IDC_CHECK_RANDOM_YROT           1272
#define IDC_CHECK_RANDOM_ZROT           1273
#define IDC_CHECK_RANDOM_ZTRANS         1274
#define IDC_CHECK_GROUP                 1275
#define IDC_CHECK_GROUP_DELETE          1276
#define IDC_CHECK_GROUP_COPY            1277
#define IDC_CHECK_GROUP_PASTE           1278
#define IDC_CHECK_TERRAIN_NORMAL        1280
#define IDC_SLIDER_GROUP_RADIUS         1281
#define IDC_EDIT_GROUP_RADIUS           1282
#define IDC_BTN_DELETE                  1283
#define IDC_LIST_OBJECT                 1285
#define IDC_BUTTON_RESET                1286
#define IDC_CHECK_SHOW_SKYBOX           1287
#define IDC_COMBO_KIND                  1288
#define IDC_RADIO_MESH4                 1289
#define IDC_RADIO_MESH6                 1290
#define IDC_RADIO_MESH8                 1291
#define IDC_EDIT_FATIGUE_TYPE           1293
#define IDC_EDIT_FATIGUE_DEBUFF         1294
#define IDC_EDIT_FATIGUE                1294
#define IDC_EDIT_FATIGUE_STIME          1295
#define IDC_EDIT_FATIGUE_ATIME          1296
#define IDC_EDIT_FATIGUE_POINT          1297
#define IDC_COMBO_ELE_TYPE              1297
#define IDC_EDIT_ELE_TIME               1298
#define IDC_EDIT_FATIGUE_POINT2         1298
#define IDC_EDIT_CAMERA_DIST_MAX_LV     1298
#define IDC_LIST_ZONE                   1299
#define IDC_EDIT_MAPID_ADD              1299
#define IDC_EDIT_ZONE_LOOPTIME          1300
#define IDC_CHECK_VIEW_DIGIMON          1300
#define IDC_EDIT_FATIGUE_TYPE3          1300
#define IDC_EDIT_MAPNAME_ADD            1300
#define IDC_EDIT_KILLGEN_DISP           1301
#define IDC_EDIT_MAPNAME_ADD2           1301
#define IDC_EDIT_Table_MAPNAME          1301
#define IDC_STATIC_MOVE                 1303
#define IDC_COMBO_PORTAL_TYPE           1304
#define IDC_EDIT_OBJECT_FACTOR1         1305
#define IDC_EDIT_OBJECT_FACTOR2         1306
#define IDC_EDIT_OBJECT_FACTOR3         1307
#define IDC_EDIT_OBJECT_FACTOR_CNT1     1308
#define IDC_EDIT_OBJECT_FACTOR_CNT2     1309
#define IDC_EDIT_OBJECT_FACTOR_CNT3     1310
#define IDC_COMBO_OBJECT_OPEN_TYPE1     1311
#define IDC_EDIT_OBJECT_SEQUENCE        1312
#define IDC_COMBO_OBJECT_OPEN_TYPE2     1313
#define IDC_COMBO_OBJECT_OPEN_TYPE3     1314
#define IDC_INS_REGEN_TYPE              1315
#define IDC_STATIC_OBJECT_UNIQID        1316
#define IDC_BUTTON1                     1317
#define IDC_OBJECT_FACTOR_ADD           1317
#define IDC_BUTTON_APPLY_BUFFREGION     1317
#define IDC_BUTTON_OPEN_DIALOG          1317
#define IDC_OBJECT_FATOR_TREE           1318
#define IDC_BUTTON_OPEN_DIALOG2         1318
#define IDC_OBJECT_FACTOR_ADD2          1319
#define IDC_OBJECT_FACTOR_CHANGE        1319
#define IDC_ADD_MAPID_BUTTON            1320
#define IDC_MAP_ID_ADD_GROUP_TXT        1321
#define IDC_ADD_MAPID_EDIT              1322
#define IDC_MAP_ID_TXT                  1322
#define IDC_ADD_MAPE_NAME_EDIT          1323
#define IDC_MAP_NAME_TXT                1323
#define IDC_CHECK_USE_OBJECTSNAP        1324
#define IDC_SLIDER1                     1326
#define IDC_SLIDER_GIZMO_SENCE          1326
#define IDC_SLIDER_RATE_CAM_HEIGHT      1326
#define IDC_SLIDER_BUFFREGION_RADIUS    1326
#define IDC_SLIDER_SELECT_OPACITY       1327
#define IDC_SLIDER_RATE_CAM_HEIGHT2     1327
#define IDC_BASIC_COORD                 1328
#define IDC_CHECK_OBJUPDATE             1329
#define IDC_CHECK_RENDER_MONSTERREGION  1330
#define IDC_CHECK_SHOW_COLLISIONBOX     1331
#define IDC_CHECK_SHOW_COLLISIONBOX2    1332
#define IDC_CHECK_COPY_NOMOVE           1332
#define IDC_EDIT_BUFFREGION_CENTERY     1333
#define IDC_PATHCNT                     1334
#define IDC_EDIT_BUFFREGION_RADIUS      1334
#define IDC_OBJECT_CNT                  1335
#define IDC_EDIT_BUFFREGION_BUFFERIDX   1335
#define IDC_EDIT_BUFFREGION_REQUIRE_1   1336
#define IDC_EDIT_BUFFREGION_REQUIRE_2   1338
#define IDC_EDIT_BUFFREGION_LAYER       1339
#define IDC_EDIT_BUFFREGION_TIME        1340
#define IDC_EDIT_BUFFREGION_CENTERX     1341
#define IDC_COMBO_APPLYTYPE             1342
#define IDC_EDIT_DEST_TGA               1343
#define IDC_EDIT_BUFFREGION_ACT         1343
#define IDC_BUTTON_TGA_TO_EMR           1344
#define IDC_EDIT_MAPID                  1345
#define IDC_EDIT_DEST_EMR               1346
#define IDC_BUTTON_OPEN_BUFF_REGION_RESOURCE 1346
#define IDC_EDIT_MAPID2                 1347
#define IDC_EDIT_BUFF_REGION_NIF        1347
#define IDC_BUTTON_EMR_TO_TGA           1348
#define IDC_EDIT_OBJECT_UNIQ_ID         1348
#define IDC_COMBO_APPLY_DETAIL          1350
#define IDC_COMBO2                      1352
#define IDC_LIST                        1354
#define IDC_CHECK_SHOW_Occluder         1355
#define IDC_EDIT_BUFFREGION_INDEX       1356
#define IDC_CHECK_XGCONSUME             1357
#define IDC_CHECK2                      1358
#define IDC_CHECK_BATTLETAG_USE         1358
#define ID_PROJECT_NEW                  32771
#define ID_PROJECT_LOAD                 32772
#define ID_PROJECT_NEW32773             32773
#define ID_32774                        32774
#define ID_CAMERA_RESET                 32775
#define ID_ICON_CAMERA_RESET            32776
#define ID_VIEW_WORLDVIEW               32780
#define ID_32782                        32782
#define ID_32783                        32783
#define ID_32787                        32787
#define ID_32789                        32789
#define ID_Menu                         32793
#define ID_VIEW_DSF                     32794
#define ID_VIEW_                        32795
#define ID_VIEW_GRIDLINETOGGLE          32796
#define ID_BUTTON32798                  32798
#define ID_CONFIG                       32798
#define ID_CONFIG32799                  32799
#define ID_CONFIG_SETTING               32800
#define ID__                            32801
#define ID_FILE_SAVEAS                  32802
#define ID_BUTTON32803                  32803
#define ID_BUTTON32806                  32806
#define ID_BUTTON32807                  32807
#define ID_FILE_LOADAS                  32808
#define ID_32809                        32809
#define ID_32810                        32810
#define ID_POPMENU_TREEITEM_DEL         32812
#define ID_VIEW_PATHOBJTOGGLE           32813
#define IDC_EDIT_ORDER_NUMBER			32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1359
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
