call ..\setdirs.bat
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk asifile.cpp
%MSVC8Dir%\vc\bin\link.exe -out:asifile.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:asifile.pdb -LTCG asifile.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk sstest.c
%MSVC8Dir%\vc\bin\link.exe -out:sstest.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:sstest.pdb -LTCG sstest.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk digplay.c
%MSVC8Dir%\vc\bin\link.exe -out:digplay.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:digplay.pdb -LTCG digplay.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk dbtest.c
%MSVC8Dir%\vc\bin\link.exe -out:dbtest.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:dbtest.pdb -LTCG dbtest.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk play.c
%MSVC8Dir%\vc\bin\link.exe -out:play.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:play.pdb -LTCG play.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib mss32midi.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk streamer.c
%MSVC8Dir%\vc\bin\link.exe -out:streamer.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:streamer.pdb -LTCG streamer.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk dlsplay.c
%MSVC8Dir%\vc\bin\link.exe -out:dlsplay.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:dlsplay.pdb -LTCG dlsplay.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib mss32midi.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk filter.cpp
%MSVC8Dir%\vc\bin\link.exe -out:filter.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:filter.pdb -LTCG filter.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk custom_filter.cpp
%MSVC8Dir%\vc\bin\link.exe -out:custom_filter.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:custom_filter.pdb -LTCG custom_filter.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk multiflt.cpp
%MSVC8Dir%\vc\bin\link.exe -out:multiflt.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:multiflt.pdb -LTCG multiflt.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk record.c
%MSVC8Dir%\vc\bin\link.exe -out:record.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:record.pdb -LTCG record.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk sidechain.cpp
%MSVC8Dir%\vc\bin\link.exe -out:sidechain.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:sidechain.pdb -LTCG sidechain.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk eventtest.cpp
%MSVC8Dir%\vc\bin\link.exe -out:eventtest.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:eventtest.pdb -LTCG eventtest.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk eventmultiple.cpp
%MSVC8Dir%\vc\bin\link.exe -out:eventmultiple.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:eventmultiple.pdb -LTCG eventmultiple.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk eventexternal.cpp
%MSVC8Dir%\vc\bin\link.exe -out:eventexternal.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:eventexternal.pdb -LTCG eventexternal.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk eventstreamerror.cpp
%MSVC8Dir%\vc\bin\link.exe -out:eventstreamerror.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:eventstreamerror.pdb -LTCG eventstreamerror.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk auditiontest.cpp
%MSVC8Dir%\vc\bin\link.exe -out:auditiontest.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:auditiontest.pdb -LTCG auditiontest.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib aud32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk demo.c
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include" -nologo  -D__RADRES__ -I..\sdk -fo demo.res demo.rc
%MSVC8Dir%\vc\bin\link.exe -out:demo.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:demo.pdb -LTCG demo.obj demo.res user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib mss32midi.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk examms.cpp
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include" -nologo  -D__RADRES__ -I..\sdk -fo examms.res examms.rc
%MSVC8Dir%\vc\bin\link.exe -out:examms.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:examms.pdb -LTCG examms.obj examms.res user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib comctl32.lib comdlg32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk msschat.c
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include" -nologo  -D__RADRES__ -I..\sdk -fo msschat.res msschat.rc
%MSVC8Dir%\vc\bin\link.exe -out:msschat.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:msschat.pdb -LTCG msschat.obj msschat.res user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib comctl32.lib comdlg32.lib wsock32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk msschtc.cpp
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include" -nologo  -D__RADRES__ -I..\sdk -fo msschtc.res msschtc.rc
%MSVC8Dir%\vc\bin\link.exe -out:msschtc.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:msschtc.pdb -LTCG msschtc.obj msschtc.res user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib comctl32.lib comdlg32.lib wsock32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk msschts.cpp
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include" -nologo  -D__RADRES__ -I..\sdk -fo msschts.res msschts.rc
%MSVC8Dir%\vc\bin\link.exe -out:msschts.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:msschts.pdb -LTCG msschts.obj msschts.res user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib comctl32.lib comdlg32.lib wsock32.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk quick.c
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include" -nologo  -D__RADRES__ -I..\sdk -fo quick.res quick.rc
%MSVC8Dir%\vc\bin\link.exe -out:quick.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:quick.pdb -LTCG quick.obj quick.res user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib mss32midi.lib -LIBPATH:C:/devel/projects/mss/build/win
%MSVC8Dir%\vc\bin\cl.exe -Z7 -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Oxb2 -O2 -DNDEBUG -Z7 -D__RADFINAL__ -D__RADINEXE__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -I..\sdk eax4exam.cpp
%MSVC8Dir%\vc\bin\link.exe -out:eax4exam.exe -fixed  -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -pdb:eax4exam.pdb -LTCG eax4exam.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmt.lib -libpath:..\..\lib mss32.lib -LIBPATH:C:/devel/projects/mss/build/win
