#pragma once

#define STR_IN_NOTTEXT				L""
#define STR_IN_WINDOW_TITLE			L"D-Player"
#define STR_IN_CUR_FILE				L"현재 파일 :"
#define STR_IN_FULL_INSTALL			L"전체 진행률"
#define STR_IN_READY_INSTALL		L"설치 준비중"
#define STR_IN_UPDATE				L"업데이트 준비"
#define STR_IN_START				L"실행 준비중"
#define STR_IN_INSTALL				L"파일 설치중"
#define STR_IN_PACK					L"파일 패킹중"
#define STR_IN_FILE_CHECK			L"파일 체크중"
#define STR_IN_CHECK				L"점검 중"
#define STR_IN_DOWN					L"파일 다운로드"
#define STR_IN_GAME_PATH			L"게임설치파일을 다운로드받을 디렉토리를 선택하십시오"
#define STR_IN_RETRY				L"     재시도 [ %d회 ]"
#define STR_IN_SUCCESS_INSTALL		L"게임 설치가 완료 되었습니다"
#define STR_IN_SUCCESS_UPDATE		L"게임 업데이트가 완료 되었습니다"
#define	STR_IN_OFFLINE				L"인터넷 연결이 끊어졌습니다."
#define STR_IN_ISEXECUTE			L"이미 게임이 실행중입니다."
#define RUN_FAIL					L"파라미터 오류"
#define USERTYPE_ERROR				L"잘못된 유저 타입입니다"
#define SERVER_ERROR				L"잘못된 서버 타입입니다"
#define UNZIP_FILE_OPEN_ERROR		L"압축파일을 열지 못하였습니다. 런처를 다시 시작해 주세요 (%s)"
#define UNZIP_ERROR					L"압축파일 해제에 실패하였습니다. 런처를 다시 시작해 주세요 (%s)"

#define ERROR_FULL_CLIENT_NO_EXE	L"설치 파일이 서버에 존재하지 않습니다."
#define STR_ALREADY_START			L"이미 게임 런처가 실행중입니다."
#define STR_DO_EXIT_GAME			L"먼저 Digimon Masters Online 를 종료하시고 실행하십시요."

#define STR_IN_STARTPAGE_OUR		L"     선택게임을 시작페이지로"
#define STR_IN_STARTPAGE_NAVER		L"     네이버를 시작페이지로"

#define STR_MESSAGE_INSTALL_URL				L"게임이 설치 되어있지 않습니다. 게임 설치파일을 다운로드 하여 설치해 주세요."
#define STR_MESSAGE_START_WEB				L"홈페이지에서 게임을 실행해 주세요."
#define STR_MESSAGE_NOT_INSTALL				L"게임이 설치되어있지 않습니다."
#define STR_MESSAGE_CANCEL					L"설치가 취소 되었습니다."
#define STR_MESSAGE_NO_EXE					L"실행 파일이 존재하지 않습니다."

#define STR_ERROR							L"런처 오류"
#define STR_FAIL_VERSION_CHECK				L"런처 버젼체크 오류.\n다시 시도 해 주십시오."
#define STR_FAIL_PACKER_DOWNLOAD			L"UpdateManager.exe 파일을 다운로드 하지 못하였습니다.\n다시 시도 해 주십시오."
#define STR_FAIL							L"실패"
#define STR_FAIL_PACK						L"패킹 실패"
#define STR_FAIL_START						L"웹에서 로그인후 실행해주세요."	
#define STR_FAIL_LINK						L"바로 가기 생성 실패"
#define STR_FAIL_THREAD						L"쓰래드 생성 실패"
#define STR_FAIL_INSTALL					L"파일 설치 횟수를 초과 하였습니다 : (에러번호 : %ld )"
#define STR_FAIL_CONNECT_INTERNET			L"인터넷 연결에 실패 하였습니다"
#define STR_FAIL_CONNECT_FILE_SERVER		L"서버 파일 접근 실패 : %s"
#define STR_FAIL_CONNECT_SERVER				L"%s 파일 접근 실패 : 알수 없는 에러 입니다 ( 에러번호 : %ld )"
#define STR_FAIL_PATCHINFO					L"패치 정보를 받아오는데 실패하였습니다."
#define STR_FAIL_CLIENT_PATCHINFO			L"클라이언트내에 패치 정보가 존재하지 않습니다."
#define STR_FAIL_DOWNSDK					L"다운로드 SDK오류"
#define STR_FAIL_DISK						L"게임 설치를 위한 디스크 용량이 부족합니다. (5GB이상의 용량을 확보해 주세요)"
#define STR_FAIL_LAUNCHER_REG				L"레지스트리에 설정된 런처경로가 존재하지 않습니다. 런처를 수동설치해주세요"
#define STR_FAIL_GAME_REG					L"레지스트리에 게임설치 경로가 존재하지 않습니다."
#define STR_FAIL_PATCHINFO_OLD				L"클라이언트에 버젼 너무 오래되었습니다. : 게임 재설치 또는 수동패치를 해주세요"
#define STR_FAIL_PATCHINFO_CLIENT			L"클라이언트에 버젼 정보가 손상되었습니다 : 게임 재설치 또는 수동패치를 해주세요"
#define STR_FAIL_EXEFILE_VERSION			L"실행파일 버젼이 다릅니다. 게임런처를 다시 실행해 주세요"

#define STR_PLAYGAME_ERROR_FILE_NOT_FOUND		L"게임시작에러 : 실행파일이 존재하지 않습니다. 잠시후에 시도하세요."
#define STR_PLAYGAME_ERROR_PATH_NOT_FOUND		L"게임시작에러 : 경로가 틀립니다."
#define STR_PLAYGAME_ERROR_NOT_ENOUGH_MEMORY	L"게임시작에러 : 메모리가 부족합니다."
#define STR_PLAYGAME_ERROR_BAD_EXE_FORMAT		L"게임시작에러 : 실행화일이 잘못 되었습니다."
#define STR_PLAYGAME_ERROR_DEFAULT				L"게임시작에러 : 번호 %ld"

#define STR_PACKER_ERRO_DEFAULT					L"런처 패치 에러 : 번호 %ld"

#define STR_FAIL_RUN_EXEFILE					L"Visual Studio 2015용 Visual C++ 재배포 가능 패키지(x86) 설치 파일이 없습니다."

#define STR_DIGIMONMASTERS_KOR			L"디지몬 마스터즈"
#define STR_DIGIMONRPG_KOR				L"디지몬 RPG"
#define STR_NOIR_KOR					L"느와르 온라인"

#define STR_DIGIMONMASTERS_ENG			L"DigimonMasters"
#define STR_DIGIMONRPG_ENG				L"DigimonRPG"
#define STR_NOIR_ENG					L"Noir"

#define STR_BUTTON_HOMEPAGE				L"홈페이지"
#define STR_BUTTON_PATCH				L"게임소식"
#define STR_BUTTON_OPTION				L"옵션"
#define STR_BUTTON_OK					L"확인"
#define STR_CLIENT_PATH_NUMBER			L"Client Path Number : %d"
