//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SequnceTool.rc
//
#define IDD_ABOUTBOX                    100
#define IDD__DLG_COPY_DIGIMON           103
#define IDR_MAINFRAME                   128
#define IDR_SequnceToolTYPE             129
#define IDD_DLG_CONTROL                 130
#define IDD_DLG_ANIMATION               131
#define IDD_DLG_ETC                     132
#define IDD_DLG_INSERT_EVENT            133
#define IDD_DLG_PART                    134
#define IDD_DLG_INSERT_SHADER           135
#define IDC_BUTTON_SAVE                 1000
#define IDC_BUTTON_SAVE_EXCEL           1001
#define IDC_BUTTON_SAVE_HEIGHTEXCEL     1002
#define IDC_LIST_MODEL                  1004
#define IDC_BUTTON_RESETMODEL           1005
#define IDC_BUTTON_NONELIST_DELETEMODEL 1006
#define IDC_EDIT_SCALE                  1007
#define IDC_SPIN_SCALE                  1008
#define IDC_EDIT_OFFSET_Y               1009
#define IDC_BUTTON_CHECK_ANI            1009
#define IDC_EDIT_HEIGHT                 1010
#define IDC_SPIN_OFFSET_Y               1010
#define IDC_SPIN_HEIGHT                 1011
#define IDC_EDIT_OFFSET_Z               1011
#define IDC_EDIT_WIDTH                  1012
#define IDC_SPIN_OFFSET_Z               1012
#define IDC_SPIN_WIDTH                  1013
#define IDC_EDIT_EFF0_Y                 1013
#define IDC_CHECK_HIDE_ABV              1014
#define IDC_SPIN_EFF0_Y                 1014
#define IDC_CHECK_HIDE_CLIENT           1015
#define IDC_EDIT_EFF0_Z                 1015
#define IDC_SLIDER_TIME                 1016
#define IDC_EDIT_DEST_DIST              1016
#define IDC_SPIN_DEST_DIST              1017
#define IDC_SPIN_EFF0_Z                 1017
#define IDC_EDIT_EFF1_Y                 1018
#define IDC_BUTTON_CHECK_EVENT          1018
#define IDC_CHECK_VIEW_DEST             1019
#define IDC_SPIN_EFF1_Y                 1019
#define IDC_LIST_SEQUENCE               1020
#define IDC_EDIT_CHAR_HEIGHT            1020
#define IDC_EDIT_TIME                   1021
#define IDC_EDIT_FIND                   1021
#define IDC_CHECK_PLAY                  1022
#define IDC_BUTTON_CHECK_EVENT2         1022
#define IDC_BUTTON_BG                   1022
#define IDC_LIST_EVENT                  1023
#define IDC_BUTTON_SETTIME              1024
#define IDC_BUTTON_NEW_EVENT            1025
#define IDC_BUTTON_EFFECT_FILE          1025
#define IDC_BUTTON_DEL_EVENT            1026
#define IDC_LIST_FE_LIST                1026
#define IDC_BUTTON_SOUND_FILE           1027
#define IDC_CHECK_LOOPPLAY              1027
#define IDC_LIST_DY_SOUND               1028
#define IDC_EDIT_EFF1_Z                 1028
#define IDC_RADIO_LOOP                  1029
#define IDC_BUTTON_STOPFRAME            1029
#define IDC_RADIO_ONCE                  1030
#define IDC_LIST_DY_EFFECT              1030
#define IDC_BUTTON_FE_LOAD              1031
#define IDC_BUTTON_DEL_EFFECT           1031
#define IDC_CHECK_CHARPOS               1032
#define IDC_BUTTON_FE_DEL               1032
#define IDC_CHECK_USEOFFSET             1033
#define IDC_BUTTON_ADD_SHADER           1033
#define IDC_EDIT_OFFSET_X               1034
#define IDC_SPIN_OFFSET_X               1035
#define IDC_TREE1                       1036
#define IDC_EDIT_SPEED                  1036
#define IDC_SPIN_SPEED                  1037
#define IDC_EDIT_EFFECTSCALE            1038
#define IDC_COMBO_DEST_ANI              1039
#define IDC_SPIN_EFFECTSCALE            1039
#define IDC_BUTTON_SRC_ATTDIST          1040
#define IDC_CHECK_GAMESCALE             1040
#define IDC_BUTTON_SRC_ATTDIST2         1041
#define IDC_SPIN_EFF1_Z                 1041
#define IDC_EDIT_EFF0_X                 1042
#define IDC_SPIN_EFF0_X                 1043
#define IDC_EDIT_EFF1_X                 1044
#define IDC_COMBO_STARTPOS              1045
#define IDC_SPIN_EFF1_X                 1046
#define IDC_BUTTON_FOLDER               1047
#define IDC_EDIT_FADETIME               1047
#define IDC_COMBO_ACTION                1048
#define IDC_SPIN_FADETIME               1048
#define IDC_BUTTON_FIND                 1048
#define IDC_BUTTON_ATT1                 1049
#define IDC_CHECK_PLAN_VIEW             1049
#define IDC_BUTTON_SOUND_FOL            1049
#define IDC_BUTTON_SOUND_FOLDER         1049
#define IDC_BUTTON_ATT2                 1050
#define IDC_CHECK_PLAN_TOWSIDE          1050
#define IDC_BUTTON_SKILL1               1051
#define IDC_CHECK_PLAN_WIRE             1051
#define IDC_BUTTON_SKILL2               1052
#define IDC_CHECK_VIEWOFFSET            1052
#define IDC_BUTTON_SKILL3               1053
#define IDC_EDIT_EFF0_X2                1053
#define IDC_EDIT_ANILOOP                1053
#define IDC_BUTTON_SKILL4               1054
#define IDC_COMBO_EVENTTYPE             1054
#define IDC_BUTTON_FT_DIGIMON           1055
#define IDC_COMBO1                      1055
#define IDC_COMBO_DEL                   1055
#define IDC_COMBO_SHADER                1055
#define IDC_BUTTON_FT_SKILL             1056
#define IDC_COMBO_ROT                   1056
#define IDC_BUTTON_OK                   1056
#define IDC_COMBO_EFF_LEVEL             1057
#define IDC_LIST_SHADER                 1058
#define IDC_STATIC_INT_VAL1             1058
#define IDC_BUTTON_NEW_SHADER           1059
#define IDC_STATIC_FLT_VAL1             1059
#define IDC_BUTTON_DEL_SHADER           1060
#define IDC_STATIC_FLT_VAL2             1060
#define IDC_STATIC_FLT_VAL3             1061
#define IDC_STATIC_FLT_VAL4             1062
#define IDC_EDIT_FLOAT_1                1063
#define IDC_EDIT_FLOAT_2                1064
#define IDC_EDIT_FLOAT_3                1065
#define IDC_EDIT_FLOAT_4                1066
#define IDC_LIST_OBJECT                 1067
#define IDC_EDIT_INT_1                  1068
#define IDC_STATIC_STR_VAL1             1069
#define IDC_EDIT_STR_1                  1070
#define IDC_BUTTON1                     1071
#define IDC_BUTTON_STR_1                1071
#define IDC_BUTTON_COPY_DIGIMON         1071
#define IDC_BUTTON_OPEN_DIALOG          1071
#define IDC_EDIT_COPY_SRC_PATH          1072
#define IDC_EDIT_COPY_DEST_DIGIMON_ID   1073
#define IDC_EDIT_COPY_DEST_DIGIMON_NAME 1074
#define IDC_EDIT_COPY_SRC_DIGIMONID     1075
#define IDC_EDIT_COPY_SRC_DIGIMON_NAME  1076
#define IDC_BUTTON                      1077
#define IDC_BUTTON_CREATE_DIGIMON_FROM_BASE 1077

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
