
//---------------------------------------------------------------------------
#pragma once
//---------------------------------------------------------------------------

BEGIN_NAME_TABLE

typedef DmCS::DmData::CReader DataStream;
typedef DmCS::DmData::CSaver SaveStream;

typedef enum eServiceType
{
	eNone,
	eSteam,
};

typedef enum eTableType
{	
	ETABLE_BEGIN = -1,
	ETABLE_ACHIEVE,
	ETABLE_BASESTATS,
	ETABLE_BUFF,
	ETABLE_CASH_SHOP,
	ETABLE_COOLTIME,
	ETABLE_CREATE_CHARACTER,
	ETABLE_DBOOK,
	ETALBE_DEVOLUTION,
	ETABLE_DIGIMONS,
	ETABLE_DSKILL_LEVELUP,
	ETABLE_EXP,
	ETABLE_GUILD,
	ETABLE_INFINITEWAR,
	ETABLE_ITEMS,
	ETABLE_ITEMS_RANK,
	ETABLE_ITEM_CREATION,
	ETABLE_ITEMS_EXCHANGE,
	ETABLE_JUMPBUSTER,
	ETABLE_MAPSINFO,
	ETABLE_MONSTER,
	//ETABLE_TACTICS,
	//ETABLE_TALK,
	ETABLE_UITEXT,
	ETABLE_END,
}ETableType;

typedef enum eStringTableType
{
	ESTRING_BEGIN = -1,
	ESTRING_TABLE_ACHIEVE,
	ESTRING_TABLE_BUFF,
	ESTRING_TABLE_CASHSHOP,
	ESTRING_TABLE_DIGIEVO,
	ESTRING_TABLE_DIGIMON,
	ESTRING_TABLE_DIGIMON_TIP,
	ESTRING_TABLE_DIGIMON_TALK,
	ESTRING_TABLE_EMOTION,
	ESTRING_TABLE_EVENT_TALK,
	ESTRING_TABLE_GUILD,
	ESTRING_TABLE_ITEM,
	ESTRING_TABLE_ITEM_CREATION,
	ESTRING_TABLE_MAP,
	ESTRING_TABLE_MAP_REGION,
	ESTRING_TABLE_MESSAGE,
	ESTRING_TABLE_MONSTER,
	ESTRING_TABLE_NPC,
	ESTRING_TABLE_QUEST,
	ESTRING_TABLE_RIDING,
	ESTRING_TABLE_SCENE,
	ESTRING_TABLE_SEAL,
	ESTRING_TABLE_SKILL,
	ESTRING_TABLE_TAMER,
	ESTRING_TABLE_TIP,
	ESTRING_TABLE_TOOLTIP,
	ESTRING_TABLE_UITEXT,
	ESTRING_END,
}EStringTableType;

END_NAME_TABLE