call ..\setdirs.bat
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4996 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL -D__RADINEXE__ "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include  -I..\sdk milesmid.c
%WINDOWS_PLATFORM_SDK%\bin\rc.exe "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include -nologo  -D__RADRES__ -I..\sdk -fo milesmid.res milesmid.rc
%MSVC8Dir%\vc\bin\cvtres.exe /nologo /machine:X64 -out:C:/devel/projects/mss/build/win64/temps/exe64/LTCG/milesmid/milesmid.res.obj milesmid.res
%MSVC8Dir%\vc\bin\amd64\link.exe -out:milesmid.exe -fixed  -nodefaultlib -nodefaultlib -nologo -map -opt:ref -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -libpath:"%MSVC8Dir%\vc\lib\amd64" -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:"%WINDOWS_PLATFORM_SDK%\lib\x64" -libpath:"%WINDOWS_PLATFORM_SDK%\lib\amd64" -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -LTCG milesmid.obj C:\devel\projects\mss\build\win64\temps\exe64\LTCG\milesmid\milesmid.res.obj user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib -libpath:..\..\lib mss64.lib mss64midi.lib shell32.lib comdlg32.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4996 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL -D__RADINEXE__ "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include  -I..\sdk milesply.cpp
%WINDOWS_PLATFORM_SDK%\bin\rc.exe "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include -nologo  -D__RADRES__ -I..\sdk -fo milesply.res milesply.rc
%MSVC8Dir%\vc\bin\cvtres.exe /nologo /machine:X64 -out:C:/devel/projects/mss/build/win64/temps/exe64/LTCG/milesply/milesply.res.obj milesply.res
%MSVC8Dir%\vc\bin\amd64\link.exe -out:milesply.exe -fixed  -nodefaultlib -nodefaultlib -nologo -map -opt:ref -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -libpath:"%MSVC8Dir%\vc\lib\amd64" -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:"%WINDOWS_PLATFORM_SDK%\lib\x64" -libpath:"%WINDOWS_PLATFORM_SDK%\lib\amd64" -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -LTCG milesply.obj C:\devel\projects\mss\build\win64\temps\exe64\LTCG\milesply\milesply.res.obj user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib -libpath:..\..\lib mss64.lib mss64midi.lib comdlg32.lib comctl32.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4996 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL -D__RADINEXE__ "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include  -I..\sdk wavmux.cpp
%MSVC8Dir%\vc\bin\amd64\link.exe -out:wavmux.exe -fixed   -nodefaultlib -nodefaultlib -nologo -map -opt:ref -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -libpath:"%MSVC8Dir%\vc\lib\amd64" -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:"%WINDOWS_PLATFORM_SDK%\lib\x64" -libpath:"%WINDOWS_PLATFORM_SDK%\lib\amd64" -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -LTCG wavmux.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib -libpath:..\..\lib mss64.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4996 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL -D__RADINEXE__ "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include  -I..\sdk makeloop.cpp
%MSVC8Dir%\vc\bin\amd64\link.exe -out:makeloop.exe -fixed   -nodefaultlib -nodefaultlib -nologo -map -opt:ref -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -libpath:"%MSVC8Dir%\vc\lib\amd64" -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:"%WINDOWS_PLATFORM_SDK%\lib\x64" -libpath:"%WINDOWS_PLATFORM_SDK%\lib\amd64" -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -LTCG makeloop.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib -libpath:..\..\lib mss64.lib mss64midi.lib -LIBPATH:C:/devel/projects/mss/build/win64
%MSVC8Dir%\vc\bin\amd64\cl.exe -Z7 -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4996 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL -D__RADINEXE__ "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include  -I..\sdk midiechw.cpp
%WINDOWS_PLATFORM_SDK%\bin\rc.exe "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include -nologo  -D__RADRES__ -I..\sdk -fo midiechw.res midiechw.rc
%MSVC8Dir%\vc\bin\cvtres.exe /nologo /machine:X64 -out:C:/devel/projects/mss/build/win64/temps/exe64/LTCG/midiechw/midiechw.res.obj midiechw.res
%MSVC8Dir%\vc\bin\amd64\link.exe -out:midiechw.exe -fixed  -nodefaultlib -nodefaultlib -nologo -map -opt:ref -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -libpath:"%MSVC8Dir%\vc\lib\amd64" -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:"%WINDOWS_PLATFORM_SDK%\lib\x64" -libpath:"%WINDOWS_PLATFORM_SDK%\lib\amd64" -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -LTCG midiechw.obj C:\devel\projects\mss\build\win64\temps\exe64\LTCG\midiechw\midiechw.res.obj user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib -libpath:..\..\lib mss64.lib mss64midi.lib winmm.lib dsound.lib comdlg32.lib -LIBPATH:C:/devel/projects/mss/build/win64
