<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DProject</RootNamespace>
    <AssemblyName>DProject.CSharp.Gamebryo</AssemblyName>
    <Configurations>Debug;Release;Release_English</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release_English'">
    <Optimize>true</Optimize>
    <DebugType>portable</DebugType>
    <DefineConstants>$(DefineConstants);RELEASE_ENGLISH;VERSION_ENGLISH</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="D:\Gamebryo2.3\GamebryoSharp\src\GamebryoSharp.Core\GamebryoSharp.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
