namespace ItemEditor.Models;

public sealed record EffectOption(int Id, string Name)
{
    public override string ToString() => Name;
}

public static class SkillEffectCatalog
{
    public static IReadOnlyList<EffectOption> ApplyOptions { get; } =
    [
        new(0, "Event item"),
        new(1, "HP"),
        new(2, "DS"),
        new(3, "Max HP"),
        new(4, "Max DS"),
        new(5, "Attack"),
        new(6, "Critical"),
        new(7, "Defense"),
        new(8, "Evasion"),
        new(9, "Move Speed"),
        new(10, "Attack Speed"),
        new(11, "Attack Range"),
        new(12, "Hit Rate"),
        new(13, "Fatigue"),
        new(14, "Friendliness"),
        new(15, "EXP"),
        new(16, "Attribute Apply Rate"),
        new(17, "Block"),
        new(18, "Normal Damage"),
        new(19, "Normal Attack Evasion"),
        new(20, "All Parameters"),
        new(21, "Skill Evasion"),
        new(22, "Skill Damage Reduction"),
        new(23, "Skill Accuracy"),
        new(24, "Skill Damage"),
        new(25, "Skill Critical"),
        new(26, "HP Recovery"),
        new(27, "DS Recovery"),
        new(28, "Normal Damage Reduction"),
        new(29, "Normal Hit Rate"),
        new(30, "DS Natural Recovery"),
        new(31, "HP Natural Recovery"),
        new(32, "Abnormal Status"),
        new(33, "Unbeatable"),
        new(34, "Attribute EXP"),
        new(35, "Code Crown Gauge"),
        new(36, "Cross Loader"),
        new(37, "DOT Damage"),
        new(38, "Delay Damage"),
        new(39, "Stun"),
        new(40, "Damage Reflect"),
        new(41, "Damage Absorb"),
        new(42, "HP Based Damage"),
        new(43, "Attribute Damage"),
        new(44, "HP Based Defense"),
        new(45, "Attribute Defense"),
        new(46, "Provoke"),
        new(47, "Insurance Recovery"),
        new(48, "Critical Damage"),
        new(49, "Received Damage Reduction"),
        new(51, "Guild Shout"),
        new(52, "Guild Member Up"),
        new(53, "Guild Summon"),
        new(54, "Guild Name Color"),
        new(61, "Guild Nature EXP"),
        new(62, "Guild Scan Cost Down"),
        new(63, "Guild Scan Money Up"),
        new(64, "Guild Hatch Up"),
        new(65, "Guild Crop Bit Up"),
        new(66, "Guild Move Up"),
        new(67, "Guild Enhance Cost Down"),
        new(68, "Guild Enhance Rate Up"),
        new(71, "Weakness"),
        new(72, "Attribute Damage"),
        new(73, "Attribute Reflect"),
        new(74, "Attribute Absorb"),
        new(75, "Silence"),
        new(76, "All Skill Damage Decrease"),
        new(77, "Specific Skill Damage Decrease"),
        new(78, "Specific Skill Damage Increase"),
        new(79, "Nature Shield"),
        new(80, "X Gauge"),
        new(81, "X Crystal"),
        new(82, "Region Buff Dummy"),
        new(83, "Evolution Damage Increase"),
        new(84, "Nature Damage Increase"),
        new(85, "Fixed Move Speed")
    ];

    public static IReadOnlyList<EffectOption> MethodOptions { get; } =
    [
        new(0, "None"),
        new(1, "Damage calculation"),
        new(2, "Skill damage calculation"),
        new(10, "Tamer skill damage calculation"),
        new(101, "Add flat amount"),
        new(102, "Increase by percent"),
        new(103, "Scale by percent"),
        new(104, "Set fixed amount"),
        new(105, "Increase by percent"),
        new(106, "Increase by percent"),
        new(107, "Abnormal status"),
        new(108, "Use current value"),
        new(200, "No formula apply"),
        new(201, "Add amount for duration"),
        new(202, "Increase percent for duration"),
        new(203, "Scale percent for duration"),
        new(204, "Set amount for duration"),
        new(205, "DOT formula"),
        new(206, "Skill damage value buff"),
        new(207, "Skill damage rate buff"),
        new(208, "Increase duration"),
        new(209, "Increase percent"),
        new(215, "Unbeatable"),
        new(301, "Subtract flat amount"),
        new(302, "Debuff percent"),
        new(303, "Apply percent"),
        new(401, "Event sync"),
        new(402, "Temporary scale change"),
        new(403, "Percent formula"),
        new(404, "Debuff formula"),
        new(501, "Special formula")
    ];

    public static string ApplyLabel(int value)
        => ApplyOptions.FirstOrDefault(x => x.Id == value)?.Name ?? $"Unknown apply {value}";

    public static string ApplyToken(int value)
        => value switch
        {
            0 => "FMCOMMON_EVENT_ITEM",
            1 => "APPLY_HP",
            2 => "APPLY_DS",
            3 => "APPLY_MAXHP",
            4 => "APPLY_MAXDS",
            5 => "APPLY_AP",
            6 => "APPLY_CA",
            7 => "APPLY_DP",
            8 => "APPLY_EV",
            9 => "APPLY_MS",
            10 => "APPLY_AS",
            11 => "APPLY_AR",
            12 => "APPLY_HT",
            13 => "APPLY_FP",
            14 => "APPLY_FS",
            15 => "APPLY_EXP",
            16 => "APPLY_POWERAPPLYRATE",
            17 => "APPLY_BL",
            18 => "APPLY_DA",
            19 => "APPLY_ER",
            20 => "APPLY_AllParam",
            21 => "APPLY_SER",
            22 => "APPLY_SDR",
            23 => "APPLY_SRR",
            24 => "APPLY_SCD",
            25 => "APPLY_SCR",
            26 => "APPLY_HRR",
            27 => "APPLY_DRR",
            28 => "APPLY_MDA",
            29 => "APPLY_HR",
            30 => "APPLY_DSN",
            31 => "APPLY_HPN",
            32 => "APPLY_STA",
            33 => "APPLY_UB",
            34 => "APPLY_ATTRIBUTTE",
            35 => "APPLY_CC",
            36 => "APPLY_CR",
            37 => "APPLY_DOT",
            38 => "APPLY_DOT2",
            39 => "APPLY_STUN",
            40 => "APPLY_DR",
            41 => "APPLY_AB",
            42 => "APPLY_HPDMG",
            43 => "APPLY_ATDMG",
            44 => "APPLY_HPDEF",
            45 => "APPLY_ATDEF",
            46 => "APPLY_PROVOKE",
            47 => "APPLY_INSURANCE",
            48 => "APPLY_CAT",
            49 => "APPLY_RDD",
            51 => "GUILD_SHOUT",
            52 => "GUILD_MEMBERUP",
            53 => "GUILD_SUMMON",
            54 => "GUILD_NAMECOLOR",
            61 => "GUILD_NATUREUP",
            62 => "GUILD_SCANREDUCE",
            63 => "GUILD_SCANBITUP",
            64 => "GUILD_HATCHUP",
            65 => "GUILD_CROPBITUP",
            66 => "GUILD_MOVEUP",
            67 => "GUILD_INCHAPAYREDUCE",
            68 => "GUILD_INCHARATEUP",
            71 => "APPLY_WEAKNESS",
            72 => "APPLY_ATTRIBUTEDAMAGE",
            73 => "APPLY_ATTRIBUTEDR",
            74 => "APPLY_ATTRIBUTEDS",
            75 => "APPLY_SILENCE",
            76 => "APPLY_AllSkillDamageDecrease",
            77 => "APPLY_SpecificSkillDamageDecrease",
            78 => "APPLY_SpecificSkillDamageIncrease",
            79 => "APPLY_NatureShield",
            80 => "APPLY_XGuage",
            81 => "APPLY_XCrystal",
            82 => "APPLY_RegionBuffDummy",
            83 => "APPLY_EvoTypeDamageIncrease",
            84 => "APPLY_NatureTypeDamageIncrease",
            85 => "APPLY_FixMoveSpeed",
            _ => $"APPLY_{value}"
        };

    public static string ApplyName(int value)
        => $"{value} - {ApplyToken(value)}";

    public static string MethodLabel(ushort value)
        => MethodOptions.FirstOrDefault(x => x.Id == value)?.Name ?? $"Unknown method {value}";

    public static string MethodName(ushort value)
        => value switch
        {
            0 => "0 - none",
            1 => "Me_001 - damage calculation",
            2 => "Me_002 - skill damage calculation",
            10 => "Me_010 - tamer skill damage calculation",
            101 => "Me_101 - A=A+B",
            102 => "Me_102 - A=A+(A*B/100)",
            103 => "Me_103 - A=A*B/100",
            104 => "Me_104 - A=B",
            105 => "Me_105 - A=A+(A*B/100)",
            106 => "Me_106 - A=A+(A*B/100)",
            107 => "Me_107 - abnormal status",
            108 => "Me_108 - A=A",
            200 => "Me_200 - no formula apply",
            201 => "Me_201 - B sec, A=A+C",
            202 => "Me_202 - B sec, A=A+(A*C/100)",
            203 => "Me_203 - B sec, A=A*C/100",
            204 => "Me_204 - B sec, A=C",
            205 => "Me_205 - DOT formula",
            206 => "Me_206 - skill damage value buff",
            207 => "Me_207 - skill damage rate buff",
            208 => "Me_208 - Time=Time+(SkillLv*Apply)",
            209 => "Me_209",
            215 => "Me_215",
            301 => "Me_301 - A=A-B",
            302 => "Me_302",
            303 => "Me_303",
            401 => "Me_401 - event sync",
            402 => "Me_402 - temporary scale change",
            403 => "Me_403",
            404 => "Me_404",
            501 => "Me_501",
            _ => $"{value} - unknown method"
        };

    public static string BuildEffectSentence(SkillApplyEditor apply)
    {
        var stat = ApplyLabel(apply.A);
        return apply.Id switch
        {
            0 when apply.A == 0 && apply.B == 0 && apply.C == 0 && apply.BuffCode == 0 => "No effect",
            101 => $"{stat} +{apply.B}",
            102 or 105 or 106 or 209 => $"{stat} +{apply.B}%",
            103 => $"{stat} x{apply.B}%",
            104 => $"{stat} = {apply.B}",
            107 => $"{stat} status code {apply.B}",
            108 => $"{stat} uses current value",
            200 => $"{stat}: no formula apply",
            201 => $"{stat} +{apply.C} for {apply.B}s",
            202 => $"{stat} +{apply.C}% for {apply.B}s",
            203 => $"{stat} x{apply.C}% for {apply.B}s",
            204 => $"{stat} = {apply.C} for {apply.B}s",
            205 => $"{stat} DOT B={apply.B}, C={apply.C}",
            206 => $"{stat} +{apply.B}",
            207 => $"{stat} +{apply.B}%",
            208 => $"{stat} duration +{apply.B}",
            301 => $"{stat} -{apply.B}",
            302 or 404 => $"{stat} -{apply.B}%",
            303 => $"{stat} {apply.B}% applied",
            401 => $"{stat} event sync",
            402 => $"{stat} temporary scale {apply.B}",
            403 => $"{stat} +{apply.B}%",
            501 => $"{stat} special formula B={apply.B}, C={apply.C}",
            _ => $"{stat} B={apply.B}, C={apply.C}"
        };
    }
}
