call ..\setdirs.bat
%MSVC8Dir%\vc\bin\cl.exe -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__  -DUSE_MSS  -GS  -DUSE_RR2 -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -D__RADINDLL__  mssdbg.c msssys.c win32_rrThreads2.c win32_rrCpu.c mssevent.cpp MilesEventExec.cpp mileseventqueue.cpp mileseventsupport.cpp MilesEventBank.cpp mileseventaudition.cpp hlbank.cpp MilesEventHandle.cpp hlparse.cpp wavefile.cpp adpcm_c.cpp genericmss.cpp mss.cpp rib.cpp m3d.cpp flt.cpp miscutil.cpp mssstrm.cpp mssinput.cpp mix.cpp io.cpp win32io.cpp milesasync.cpp mssdig.cpp win32_rrAtomics.cpp win32_rrTime.cpp
%MSVC8Dir%\vc\bin\ml.exe -nologo -Cp -c -W2 -DMASM  -safeseh -coff mssa32.asm
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include" -nologo  -D__RADRES__  -DUSE_MSS  -DUSE_RR2  -fo mss.res mss.rc
%MSVC8Dir%\vc\bin\link.exe -out:mss32.dll -dll -dynamicbase -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -LTCG   mssevent.obj MilesEventExec.obj mileseventqueue.obj mileseventsupport.obj MilesEventBank.obj mileseventaudition.obj hlbank.obj MilesEventHandle.obj hlparse.obj wavefile.obj mssa32.obj adpcm_c.obj genericmss.obj mss.obj rib.obj m3d.obj flt.obj miscutil.obj mssstrm.obj mssdbg.obj mssinput.obj msssys.obj mix.obj io.obj win32io.obj milesasync.obj mssdig.obj win32_rrThreads2.obj win32_rrAtomics.obj win32_rrTime.obj win32_rrCpu.obj mss.res user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib winmm.lib ksuser.lib winmm.lib winmm.lib
%MSVC8Dir%\vc\bin\cl.exe -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__  -DUSE_MSS  -GS -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -D__RADINDLL__  msscd.c mssxdig.c mssxmidi.c mssqapi.c midilist.c midi2xmi.c dlshl.c mididbg.c mssutil.cpp dls1pars.cpp dls1syn.cpp dlsfile.cpp dlslist.cpp mssadpcm.cpp synth.cpp
%MSVC8Dir%\vc\bin\link.exe -out:mss32midi.dll -dll -dynamicbase -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -LTCG   mssutil.obj msscd.obj mssxdig.obj mssxmidi.obj mssqapi.obj dls1pars.obj dls1syn.obj dlsfile.obj dlslist.obj midilist.obj midi2xmi.obj dlshl.obj mididbg.obj mssadpcm.obj synth.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib mss32.lib winmm.lib
%MSVC8Dir%\vc\bin\cl.exe -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -D__RADINDLL__  mssdsp.c ribdll.c win32_rrAtomics.cpp bandpass.cpp allpass.cpp capture.cpp chorus.cpp flange.cpp highpass.cpp lowpass.cpp parmeq.cpp phaser.cpp reson.cpp ringmod.cpp delay.cpp shelfeq.cpp volramp.cpp gainblk.cpp sidecompress.cpp
%MSVC8Dir%\vc\bin\cl.exe -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -D__RADINDLL__  radlibc.c
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include" -nologo  -D__RADRES__  -fo mss.res mss.rc
%MSVC8Dir%\vc\bin\link.exe -out:mssdsp.flt -dll -dynamicbase -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -LTCG   mssdsp.obj ribdll.obj win32_rrAtomics.obj bandpass.obj allpass.obj capture.obj chorus.obj flange.obj highpass.obj lowpass.obj parmeq.obj phaser.obj reson.obj ringmod.obj delay.obj shelfeq.obj volramp.obj gainblk.obj sidecompress.obj radlibc.obj mss.res user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib winmm.lib
%MSVC8Dir%\vc\bin\cl.exe -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -D__RADINDLL__  ribdll.c msssrs.cpp
%MSVC8Dir%\vc\bin\cl.exe -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -D__RADINDLL__  radlibc.c
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include" -nologo  -D__RADRES__  -fo mss.res mss.rc
%MSVC8Dir%\vc\bin\link.exe -out:msssrs.flt -dll -dynamicbase -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -LTCG   msssrs.obj ribdll.obj radlibc.obj mss.res user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib winmm.lib mss32.lib
%MSVC8Dir%\vc\bin\cl.exe -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -D__RADINDLL__  ribdll.c mssdolby.cpp
%MSVC8Dir%\vc\bin\cl.exe -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -D__RADINDLL__  radlibc.c
%WINDOWS_PLATFORM_SDK%\bin\rc.exe -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include" -nologo  -D__RADRES__  -fo mss.res mss.rc
%MSVC8Dir%\vc\bin\link.exe -out:mssdolby.flt -dll -dynamicbase -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -LTCG   mssdolby.obj ribdll.obj radlibc.obj mss.res user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib winmm.lib
%MSVC8Dir%\vc\bin\cl.exe -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -D__RADINDLL__  ribdll.c msseax2.cpp msseax3.cpp msseax4.cpp
%MSVC8Dir%\vc\bin\cl.exe -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -D__RADINDLL__  radlibc.c
%MSVC8Dir%\vc\bin\link.exe -out:msseax.flt -dll -dynamicbase -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -LTCG   msseax2.obj msseax3.obj msseax4.obj ribdll.obj radlibc.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib winmm.lib mss32.lib winmm.lib
%MSVC8Dir%\vc\bin\cl.exe -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -D__RADINDLL__  ribdll.c mssds3dh.cpp
%MSVC8Dir%\vc\bin\cl.exe -nologo -c -Oi -arch:SSE -GF -Gm- -Gy -GR- -Oy- -EHs- -EHa- -EHc- -fp:fast -fp:except- -Gs- -GS -Zp8 -Zl -wd4748 -W4 -wd4201 -wd4740 -wd4100 -WX -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_USING_V110_SDK71_=1 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -I"%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I"%DXSDK_DIR%\include" -I"%MSVC8Dir%\dia sdk\include"  -D__RADINDLL__  radlibc.c
%MSVC8Dir%\vc\bin\link.exe -out:mssds3d.flt -dll -dynamicbase -nodefaultlib -nodefaultlib -nologo -opt:ref -map -machine:x86 -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4221 -ignore:4221 -manifest:no -nxcompat -safeseh -release /LARGEADDRESSAWARE -libpath:"%MSVC8Dir%\vc\lib" -LIBPATH:"%DXSDK_DIR%\lib\x86" -libpath:"%WINDOWS_PLATFORM_SDK%\lib" -libpath:"%MSVC8Dir%\dia sdk\lib" -LTCG   mssds3dh.obj ribdll.obj radlibc.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib winmm.lib dxguid.lib mss32.lib winmm.lib
