call ..\setdirs.bat
%MSVC8Dir%\vc\bin\amd64\cl.exe -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4996 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__  -DUSE_RR2 -GL "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include  -D__RADINDLL__   mssdbg.c msssys.c win32_rrThreads2.c win32_rrCpu.c adpcm_c.cpp mss.cpp genericmss.cpp rib.cpp m3d.cpp flt.cpp miscutil.cpp mssstrm.cpp wavefile.cpp mssinput.cpp mssdig.cpp mix.cpp io.cpp win32io.cpp milesasync.cpp mssevent.cpp mileseventqueue.cpp mileseventsupport.cpp MilesEventExec.cpp MilesEventBank.cpp mileseventaudition.cpp hlbank.cpp MilesEventHandle.cpp hlparse.cpp win32_rrAtomics.cpp win64_rrTime.cpp win32_rrTime.cpp
%MSVC8Dir%\vc\bin\amd64\ml64.exe -nologo -Cp -c -W3 -DMASM -DWIN64  mssa32.asm win64_rrAtomics_x64.asm
%WINDOWS_PLATFORM_SDK%\bin\rc.exe "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include -nologo  -D__RADRES__  -fo mss.res mss.rc
%MSVC8Dir%\vc\bin\cvtres.exe /nologo /machine:X64 -out:C:/devel/projects/mss/build/win64/temps/dll64/LTCG/mss64/mss64.res.obj mss.res
%MSVC8Dir%\vc\bin\amd64\link.exe -out:mss64.dll -dll -dynamicbase -nodefaultlib -nodefaultlib -nologo -map -opt:ref -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -libpath:"%MSVC8Dir%\vc\lib\amd64" -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:"%WINDOWS_PLATFORM_SDK%\lib\x64" -libpath:"%WINDOWS_PLATFORM_SDK%\lib\amd64" -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -LTCG   mssa32.obj adpcm_c.obj mss.obj genericmss.obj rib.obj m3d.obj flt.obj miscutil.obj mssstrm.obj mssdbg.obj wavefile.obj mssinput.obj mssdig.obj msssys.obj mix.obj io.obj win32io.obj milesasync.obj mssevent.obj mileseventqueue.obj mileseventsupport.obj MilesEventExec.obj MilesEventBank.obj mileseventaudition.obj hlbank.obj MilesEventHandle.obj hlparse.obj win32_rrThreads2.obj win64_rrAtomics_x64.obj win32_rrAtomics.obj win64_rrTime.obj win32_rrCpu.obj win32_rrTime.obj C:\devel\projects\mss\build\win64\temps\dll64\LTCG\mss64\mss64.res.obj user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib winmm.lib ksuser.lib winmm.lib winmm.lib
%MSVC8Dir%\vc\bin\amd64\cl.exe -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4996 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include  -D__RADINDLL__   msscd.c mssxdig.c mssxmidi.c mssqapi.c midilist.c midi2xmi.c dlshl.c mididbg.c mssutil.cpp dls1pars.cpp dls1syn.cpp dlsfile.cpp dlslist.cpp mssadpcm.cpp synth.cpp
%MSVC8Dir%\vc\bin\amd64\link.exe -out:mss64midi.dll -dll -dynamicbase -nodefaultlib -nodefaultlib -nologo -map -opt:ref -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -libpath:"%MSVC8Dir%\vc\lib\amd64" -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:"%WINDOWS_PLATFORM_SDK%\lib\x64" -libpath:"%WINDOWS_PLATFORM_SDK%\lib\amd64" -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -LTCG   mssutil.obj msscd.obj mssxdig.obj mssxmidi.obj mssqapi.obj dls1pars.obj dls1syn.obj dlsfile.obj dlslist.obj midilist.obj midi2xmi.obj dlshl.obj mididbg.obj mssadpcm.obj synth.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib mss64.lib winmm.lib
%MSVC8Dir%\vc\bin\amd64\cl.exe -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4996 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include  -D__RADINDLL__   mssdsp.c win32_rrAtomics.cpp bandpass.cpp allpass.cpp capture.cpp chorus.cpp flange.cpp highpass.cpp lowpass.cpp parmeq.cpp phaser.cpp reson.cpp ringmod.cpp delay.cpp shelfeq.cpp volramp.cpp gainblk.cpp sidecompress.cpp
%MSVC8Dir%\vc\bin\amd64\ml64.exe -nologo -Cp -c -W3 -DMASM -DWIN64  win64_rrAtomics_x64.asm
%WINDOWS_PLATFORM_SDK%\bin\rc.exe "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include -nologo  -D__RADRES__  -fo mss.res mss.rc
%MSVC8Dir%\vc\bin\cvtres.exe /nologo /machine:X64 -out:C:/devel/projects/mss/build/win64/temps/dll64/LTCG/mssdsp64/mss64dsp.res.obj mss.res
%MSVC8Dir%\vc\bin\amd64\link.exe -out:\mss64dsp.flt -dll -dynamicbase -nodefaultlib -nodefaultlib -nologo -map -opt:ref -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -libpath:"%MSVC8Dir%\vc\lib\amd64" -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:"%WINDOWS_PLATFORM_SDK%\lib\x64" -libpath:"%WINDOWS_PLATFORM_SDK%\lib\amd64" -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -LTCG   mssdsp.obj win32_rrAtomics.obj bandpass.obj allpass.obj capture.obj chorus.obj flange.obj highpass.obj lowpass.obj parmeq.obj phaser.obj reson.obj ringmod.obj delay.obj shelfeq.obj volramp.obj gainblk.obj sidecompress.obj win64_rrAtomics_x64.obj C:\devel\projects\mss\build\win64\temps\dll64\LTCG\mssdsp64\mss64dsp.res.obj user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib mss64.lib
%MSVC8Dir%\vc\bin\amd64\cl.exe -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4996 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include  -D__RADINDLL__   msssrs.cpp
%WINDOWS_PLATFORM_SDK%\bin\rc.exe "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include -nologo  -D__RADRES__  -fo mss.res mss.rc
%MSVC8Dir%\vc\bin\cvtres.exe /nologo /machine:X64 -out:C:/devel/projects/mss/build/win64/temps/dll64/LTCG/msssrs/mss64srs.res.obj mss.res
%MSVC8Dir%\vc\bin\amd64\link.exe -out:\mss64srs.flt -dll -dynamicbase -nodefaultlib -nodefaultlib -nologo -map -opt:ref -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -libpath:"%MSVC8Dir%\vc\lib\amd64" -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:"%WINDOWS_PLATFORM_SDK%\lib\x64" -libpath:"%WINDOWS_PLATFORM_SDK%\lib\amd64" -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -LTCG   msssrs.obj C:\devel\projects\mss\build\win64\temps\dll64\LTCG\msssrs\mss64srs.res.obj user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib mss64.lib
%MSVC8Dir%\vc\bin\amd64\cl.exe -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4996 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include  -D__RADINDLL__   mssdolby.cpp
%WINDOWS_PLATFORM_SDK%\bin\rc.exe "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include -nologo  -D__RADRES__  -fo mss.res mss.rc
%MSVC8Dir%\vc\bin\cvtres.exe /nologo /machine:X64 -out:C:/devel/projects/mss/build/win64/temps/dll64/LTCG/mssdolby/mss64dolby.res.obj mss.res
%MSVC8Dir%\vc\bin\amd64\link.exe -out:\mss64dolby.flt -dll -dynamicbase -nodefaultlib -nodefaultlib -nologo -map -opt:ref -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -libpath:"%MSVC8Dir%\vc\lib\amd64" -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:"%WINDOWS_PLATFORM_SDK%\lib\x64" -libpath:"%WINDOWS_PLATFORM_SDK%\lib\amd64" -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -LTCG   mssdolby.obj C:\devel\projects\mss\build\win64\temps\dll64\LTCG\mssdolby\mss64dolby.res.obj user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib mss64.lib
%MSVC8Dir%\vc\bin\amd64\cl.exe -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4996 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include  -D__RADINDLL__   msseax2.cpp msseax3.cpp msseax4.cpp
%MSVC8Dir%\vc\bin\amd64\link.exe -out:mss64eax.flt -dll -dynamicbase -nodefaultlib -nodefaultlib -nologo -map -opt:ref -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -libpath:"%MSVC8Dir%\vc\lib\amd64" -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:"%WINDOWS_PLATFORM_SDK%\lib\x64" -libpath:"%WINDOWS_PLATFORM_SDK%\lib\amd64" -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -LTCG   msseax2.obj msseax3.obj msseax4.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib mss64.lib winmm.lib
%MSVC8Dir%\vc\bin\amd64\cl.exe -nologo -c -Oi -GF -Gy -WX -Zl -Gm- -Oy- -fp:fast -fp:except- -GR- -EHs- -EHc- -wd4366 -wd4996 -wd4505 -wd4748 -W4 -wd4201 -wd4740 -wd4100 -D_WIN64 -DWIN64 -DWIN32 -D_WIN32 -D_CRT_SECURE_NO_DEPRECATE -D_SECURE_SCL=0 -D_HAS_ITERATOR_DEBUGGING=0 -Z7 -wd4748 -D_DEBUG -wd4189 -D__RADFINAL__ -GL "-I%MSVC8Dir%\vc\include" -I"%WINDOWS_PLATFORM_SDK%\include" -I%DXSDK_DIR%\include  -D__RADINDLL__   mssds3dh.cpp
%MSVC8Dir%\vc\bin\amd64\link.exe -out:mss64ds3d.flt -dll -dynamicbase -nodefaultlib -nodefaultlib -nologo -map -opt:ref -machine:x64 -nologo -incremental:no -debug -debugtype:CV -ignore:4033 -ignore:4089 -ignore:4748 -ignore:4221 -SAFESEH:NO /WX:NO -libpath:"%MSVC8Dir%\vc\lib\amd64" -LIBPATH:%DXSDK_DIR%\lib\x64 -libpath:"%WINDOWS_PLATFORM_SDK%\lib\x64" -libpath:"%WINDOWS_PLATFORM_SDK%\lib\amd64" -libpath:"%MSVC8Dir%\dia sdk\lib\amd64" -LTCG   mssds3dh.obj  user32.lib gdi32.lib kernel32.lib Ws2_32.lib Advapi32.lib libcmtd.lib mss64.lib winmm.lib dxguid.lib
