//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AutoUpgrade.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_AUTOUPGRADE_DIALOG          102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDB_START_NO                    131
#define IDB_BITMAP3                     132
#define IDB_CANCLE_DEF                  133
#define IDB_CANCLE_ON                   134
#define IDB_CANCLE_DOWN                 135
#define IDB_BITMAP6                     136
#define IDB_CANCLE_DISABLE              136
#define IDB_BITMAP7                     137
#define IDB_BITMAP8                     138
#define IDB_BITMAP9                     139
#define IDB_BITMAP10                    140
#define IDB_TH_OPTIN_D                  140
#define IDB_TH_OPTIN_C                  140
#define IDB_TH_OPTION_C                 140
#define IDB_MAIN_HK                     141
#define IDB_BITMAP12                    142
#define IDB_BITMAP13                    143
#define IDB_BITMAP14                    144
#define IDB_BITMAP15                    145
#define IDB_BITMAP16                    146
#define IDB_PRONOW                      146
#define IDB_BITMAP17                    147
#define IDB_START_DEF                   148
#define IDB_START_ON                    149
#define IDB_START_DOWN                  150
#define IDB_PRONOW2                     151
#define IDR_MAINFRAME                   152
#define IDB_PRONOW3                     152
#define IDR_MAINFRAME2                  153
#define IDB_BITMAP5                     155
#define IDB_OPTION_DISABLE              155
#define IDB_BITMAP21                    156
#define IDB_OPTION_DEF                  156
#define IDB_BITMAP22                    157
#define IDB_OPTION_ON                   157
#define IDB_BITMAP23                    158
#define IDB_OPTION_DOWN                 158
#define IDD_OPTION                      159
#define IDD_OPTION_TH                   160
#define IDB_BITMAP24                    162
#define IDB_MAIN_TW                     162
#define IDB_MAIN_TH                     164
#define IDB_CANClE_DEF_TH               167
#define IDB_CANCLE_ON_TH                168
#define IDB_CANCLE_DOWN_TH              169
#define IDB_CANCLE_DISABLE_TH           170
#define IDB_START_DEF_TH                171
#define IDB_IDB_START_ON_TH             172
#define IDB_START_ON_TH                 172
#define IDB_START_DOWN_TH               173
#define IDB_START_NO_TH                 174
#define IDB_BITMAP2                     176
#define IDB_TH_OPTION_O                 176
#define IDB_BITMAP4                     177
#define IDB_TH_OPTION_D                 177
#define IDB_TH_OPTION_N                 178
#define IDC_STATIC_HOME                 1002
#define IDC_STATIC_OPTION               1003
#define IDC_STATIC_START                1004
#define IDC_STATIC_CANCLE               1005
#define IDC_WEBVIEW                     1006
#define IDC_PROGRESS_MAIN               1007
#define IDC_PROGRESS_SUBDOWN            1008
#define IDC_PROGRESS_SUBUNZIP           1009
#define IDC_STATIC_UPDATE               1010
#define IDC_RADIO_MULTI                 1019
#define IDC_RADIO_MULTI2                1020
#define IDC_RADIO_MULTI3                1021
#define IDC_RADIO_TEXTURE               1022
#define IDC_RADIO_TEXTURE2              1023
#define IDC_RADIO_SHADOW                1025
#define IDC_RADIO_SHADOW2               1026
#define IDC_RADIO_SHADOW3               1027
#define IDC_RADIO_TERRAINSHADOW         1028
#define IDC_RADIO_TERRAINSHADOW2        1029
#define IDC_BUTTON1                     1029
#define IDC_RADIO_ACTORSIGHT            1030
#define IDC_TAIWAN_OPTION               1030
#define IDC_RADIO_ACTORSIGHT2           1031
#define IDC_RADIO_ACTORSIGHT3           1032
#define IDC_RADIO_TERRAINSIGHT          1033
#define IDC_RADIO_TERRAINSIGHT2         1034
#define IDC_COMBO2                      1034
#define IDC_RADIO_TERRAINSIGHT3         1035
#define IDC_SLIDER_GAMMA                1036
#define IDC_RADIO2                      1036
#define IDC_RADIO_SOUND                 1037
#define IDC_RADIO3                      1037
#define IDC_SLIDER_SOUND                1038
#define IDC_RADIO4                      1038
#define IDC_RADIO_SOUND2                1039
#define IDC_RADIO5                      1039
#define IDC_RADIO_BGM                   1040
#define IDC_RADIO6                      1040
#define IDC_RADIO_BGM2                  1041
#define IDC_RADIO7                      1041
#define IDC_SLIDER_SOUND2               1042
#define IDC_RADIO8                      1042
#define IDC_RADIO9                      1043
#define IDC_COMBO_LANGUAGE              1044
#define IDC_COMBO_BIT                   1045
#define IDC_CHECK_MYNAME                1046
#define IDC_CHECK_OTHERSNAME            1047
#define IDC_SLIDER3                     1047
#define IDC_CHECK_MONSTERNAME           1048
#define IDC_CHECK_NPC                   1049
#define IDC_SLIDER1                     1049
#define IDC_SLIDER2                     1050
#define IDC_RADIO1                      1051
#define IDC_RADIO10                     1052
#define IDC_SLIDER4                     1053
#define IDC_RADIO11                     1054
#define IDC_RADIO12                     1055
#define IDC_RADIO13                     1056
#define IDC_RADIO14                     1057
#define IDC_RADIO15                     1058
#define IDC_RADIO16                     1059
#define IDC_RADIO17                     1060

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
