// Copyright (c) 2007 - 2018 Wellbia.com Co., Ltd.

#include "zwave_sdk_client_stub_x64_0-inl.h"
#include "zwave_sdk_client_stub_x64_1-inl.h"
#include "zwave_sdk_client_stub_x64_2-inl.h"
#include "zwave_sdk_client_stub_x64_3-inl.h"
#include "zwave_sdk_client_stub_x64_4-inl.h"
#include "zwave_sdk_client_stub_x64_5-inl.h"
#include "zwave_sdk_client_stub_x64_6-inl.h"
#include "zwave_sdk_client_stub_x64_7-inl.h"
#include "zwave_sdk_client_stub_x64_8-inl.h"
#include "zwave_sdk_client_stub_x64_9-inl.h"
#include "zwave_sdk_client_stub_x64_10-inl.h"
#include "zwave_sdk_client_stub_x64_11-inl.h"
#include "zwave_sdk_client_stub_x64_12-inl.h"
#include "zwave_sdk_client_stub_x64_13-inl.h"
#include "zwave_sdk_client_stub_x64_14-inl.h"
#include "zwave_sdk_client_stub_x64_15-inl.h"
#include "zwave_sdk_client_stub_x64_16-inl.h"
#include "zwave_sdk_client_stub_x64_17-inl.h"
#include "zwave_sdk_client_stub_x64_18-inl.h"
