//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NiStripifyGeometry.rc
//
#define IDD_OPTIMIZE_PANEL              121
#define IDD_OPTIMIZATION_OPTIONS        500
#define IDD_OPT_STRIPIFY_OPTIONS        501
#define IDC_OPT_CHECK_REMOVEDUPPROPERTIES 1000
#define IDC_OPT_CHECK_REMOVEBADTEXTURINGPROPS 1001
#define IDC_OPT_CHECK_REMOVEMULTIMTLNODES 1002
#define IDC_OPT_CHECK_REMOVECHILDLESSNODES 1003
#define IDC_OPT_CHECK_REMOVESINGLECHILDNODES 1004
#define IDC_OPT_CHECK_MERGESIBLINGNODES 1005
#define IDC_OPT_CHECK_MERGESIBLINGTRISHAPES 1006
#define IDC_OPT_CHECK_OPTIMIZETRISHAPES 1007
#define IDC_OPT_CHECK_REMOVEEXTRAUVSETS 1008
#define IDC_OPT_CHECK_REMOVEUNNECESSARYNORMALS 1009
#define IDC_OPT_CHECK_REMOVEUNNECESSARYVISCONTROLLERS 1010
#define IDC_OPT_CHECK_REMOVEUNNECESSARYLOOKATCONTROLLERS 1011
#define IDC_OPT_CHECK_NOMERGEONALPHA    1012
#define IDC_OPT_EDIT_ANIMATIONKEYREDUCTIONTOLERANCE 1013
#define IDC_OPT_CHECK_REMOVEHIDDENBONEGEOMETRY 1014
#define IDC_OPT_CHECK_REDUCEANIMATIONKEYS 1015
#define IDC_OPT_CHECK_REMOVEUNNECESSARYEXTRADATA 1016
#define IDC_OPT_CHECK_SORTBYTEXTURINGPROP 1017
#define IDC_OPT_CHECK_STRIPIFY          1018
#define IDC_OPT_BUTTON_STRIPIFYOPTIONS  1019
#define IDC_OPT_CHECK_REMOVESGOKEEPTAGS 1020
#define IDC_OPT_RADIO_REMOVENAMES       1021
#define IDC_OPT_RADIO_NAMEUNNAMEDOBJECTS 1022
#define IDC_OPT_RADIO_LEAVENAMES        1023
#define IDC_OPT_BUTTON_RESETDEFAULTS    1024
#define IDC_OPT_COMBO_STRIPIFYPLATFORM  1025
#define IDC_OPT_RADIO_SKINHW            1025
#define IDC_OPT_COMBO_STRIPIFYALGORITHM 1026
#define IDC_OPT_RADIO_SKINSW            1026
#define IDC_OPT_COMBO_STRIPIFYCACHESIZE 1027
#define IDC_OPT_RADIO_SKINBOTH          1027
#define IDC_OPT_EDIT_STRIPIFYCACHESIZE  1028
#define IDC_OPT_EDIT_BONESPERPARTITION  1028
#define IDC_OPT_EDIT_STRIPIFYSTRIPMINSIZE 1029
#define IDC_OPT_CHECK_STRIPIFYLISTSONLY 1030
#define IDC_OPT_CHECK_STRIPIFYSTITCH    1031
#define IDC_OPT_BUTTON_UNCHECKALL       1032
#define IDC_OPT_CHECK_CREATEABVS        1033
#define IDC_OPT_CHECK_REMOVEABVPROXYGEOMETRY 1034
#define IDC_PC_NOSTRIP                  1036
#define IDC_PC_UNACCELERATED            1037
#define IDC_PC_FIRST_GEN                1038
#define IDC_PC_NEXTGEN                  1039
#define IDC_XBOX_NOSTRIP                1040
#define IDC_NEXTGENXBOX_NOSTRIP         1040
#define IDC_XBOX_STRIP                  1041
#define IDC_NEXTGENXBOX_STRIP           1041
#define IDC_OPTIMIZE_PROGRESS           1102
#define IDC_OPTIMIZE_STATIC_STRING      1155
#define IDC_OPTIMIZE_LINE_ONE           1156
#define IDC_OPTIMIZE_LINE_TWO           1157

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        502
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1037
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
